services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  tenpo-mock-service:
    build:
      context: ./mock-percentage-service
    ports:
      - "8081:8080"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - tenpo-mock-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/challenge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  pgdata: