server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/challenge
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: logging
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=30m
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html