DROP SCHEMA IF EXISTS LOGGING CASCADE;

CREATE SCHEMA IF NOT EXISTS LOGGING;

CREATE TABLE IF NOT EXISTS LOGGING.CALL_LOGS (
    ID BIGSERIAL PRIMARY KEY,
    endpoint VARCHAR(255),
    error VARCHAR(1000),
    parameters VARCHAR(1000),
    response VARCHAR(1000),
    timestamp TIMESTAMP(6)
);

GRANT ALL PRIVILEGES ON SCHEMA LOGGING TO postgres;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA LOGGING TO postgres;
